#!/usr/bin/env bash

VERSION="0.0.1"
echo "<== radio-init $VERSION ==>"

RADIO=~pi/.radio
STATION=$RADIO/$1
RAKEFILE=$RADIO/Rakefile
DPC=~pi/.dropbox_uploader

rake --trace -f $RAKEFILE init "STATION=$STATION" "ICECAST_HOST=$2" "PSK=$3 DROPBOX_CONF=$DPC"


