#!/usr/bin/env bash

STATION=~pi/.radio/$1
RAKEFILE=~pi/.radio/Rakefile
echo "=> Killing all pd-extended instances and init PureData"
echo "WARN: use radio-check $1 station to check execution"
killall pd-extended
rake --trace -f $RAKEFILE pd:start "STATION=$STATION"
