#!/usr/bin/python

from optparse import OptionParser
from subprocess import call

# PROGRAMA PRINCIPAL
PROG = "webcastPD runtime"
VERSION = "0.0.2"
description = "Script python para realizacao de um streaming em uma rede remota"
parser = OptionParser(usage='usage: %prog [OPTIONS, [ARGS]]',
                      version='%s %s' % (PROG, VERSION),
                      description=description)

# Opcoes do programa
opt =  [("H", "host", None, "host, ou ip do servidor que realizara o streaming (p.e., giss.tv ou 192.168.0.1)"),
        ("m", "music-path", None, "caminho da pasta local contendo uma lista de musicas"),
        ("l", "listen", None, "caminho do ponto de montagem a ser realizado o streaming [suporte a vorbis] (p.e. listen.ogg)"), 
        ("p", "port", None, "porta de servico (p.e. 8000 ou 8001)"),
        ("x", "password", None, "senha do servidor giss.tv"),
]

# Create a list of tuples
# to create a list of options
for word in opt:
    v = "_".join(word[1].split("-"))
    a = "-%s" % word[0]
    b = "--%s" % word[1]
    if word[2] != None:
        parser.add_option(a, b, action=word[2], help=word[3], dest=v, default=False)
        #elif word[1] == "measures":
        #    parser.add_option(a, b, action=word[2], help=word[3], dest=v, default=False, nargs=2)
    else:
        parser.add_option(a, b, help=word[3], dest=v, default=False)

# Capturar os argumentos passados pelo 
(options, args) = parser.parse_args()

#Nome da estacao vem do ponto de montagem?
#station = options.listen.split("/")
#station = station[len(station)-1]
station = options.listen.split(".ogg")[0]

# Patch de PD principal
main = ("#N canvas 1 440 424 359 10;",
        "#X text 0 0 ITS A GENERATED PATCH. DO NOT MODIFY!;",
        "#X obj 1 37 tgl 15 0 empty empty empty 17 7 0 10 -262144 -1 -1 0 1;",
        "#X obj 1 18 loadbang;",
        "#X obj 1 56 t f f;",
        "#X obj 1 214 dac~;",
        "#X msg 42 43 \; pd dsp \$1;",
        "#X obj 2 130 /home/pi/.radio/%s/station_server~ ;" % (station),
        "#X obj 2 181 /home/pi/.radio/%s/station_client~ 5000;" % (station) ,
        "#X obj 2 81 cast.player~ %s ;" % (options.music_path),
        "#X obj 2 153 t f f;",
        "#X connect 1 0 3 0;",
        "#X connect 2 0 1 0;",
        "#X connect 3 0 6 2;",
        "#X connect 3 1 5 0;",
        "#X connect 6 0 9 0;",
        "#X connect 7 0 4 0;",
        "#X connect 7 1 4 1;",
        "#X connect 8 0 6 0;",
        "#X connect 8 1 6 1;",
        "#X connect 9 0 7 0;",
        "#X connect 9 1 8 0;")

# Servidor
cast_server = ("#N canvas 1 50 1278 358 10;",
               "#X obj 37 360 oggcast~ 2 512;",
               "#X obj 37 32 inlet~;",
               "#X obj 116 30 inlet~;",
               "#X msg 255 143 server 1;",
               "#X obj 118 400 print station_server~ (frame):;",
               "#X obj 191 40 inlet;",
               "#X obj 191 64 sel 0 1;",
               "#X msg 44 81 disconnect;",
               "#X msg 223 201 vorbis 44100 2 133 128 96;",
               "#X msg 208 266 print;",
               "#X obj 192 87 t b b b b b;",
               "#X obj 37 404 outlet;",
               "#X msg 235 173 passwd %s;" %(options.password),
               "#X msg 192 231 connect %s %s %s ;" % (options.host, options.listen, options.port),
               "#X obj 47 383 tgl 15 0 empty empty empty 17 7 0 10 -262144 -1 -1 0 1;",
               "#X connect 0 0 11 0;",
               "#X connect 0 0 14 0;",
               "#X connect 0 1 4 0;",
               "#X connect 1 0 0 0;",
               "#X connect 2 0 0 1;",
               "#X connect 3 0 0 0;",
               "#X connect 5 0 6 0;",
               "#X connect 6 0 7 0;",
               "#X connect 6 1 10 0;",
               "#X connect 7 0 0 0;",
               "#X connect 8 0 0 0;",
               "#X connect 9 0 0 0;",
               "#X connect 10 0 13 0;",
               "#X connect 10 1 9 0;",
               "#X connect 10 2 8 0;",
               "#X connect 10 3 12 0;",
               "#X connect 10 4 3 0;",
               "#X connect 12 0 0 0;")


cast_server= ("#N canvas 1 50 1278 358 10;",
              "#X obj 36 61 oggcast~ 2 512;",
              "#X obj 37 32 inlet~;",
              "#X obj 116 30 inlet~;",
              "#X msg 412 87 server 1;",
              "#X obj 36 126 print station_server~:;",
              "#X obj 118 157 print station_server~ (frame):;",
              "#X obj 338 13 inlet;",
              "#X obj 338 37 sel 0 1;",
              "#X msg 257 32 disconnect;",
              "#X msg 367 143 vorbis 44100 2 133 128 96;",
              "#X msg 359 171 print;",
              "#X obj 339 60 t b b b b b;",
              "#X msg 392 114 passwd %s ;" % (options.password),
              "#X msg 317 211 connect %s %s %s ;" % (options.host, options.listen, options.port),
              "#X obj 36 188 outlet;",
              "#X connect 0 0 4 0;",
              "#X connect 0 0 14 0;",
              "#X connect 0 1 5 0;",
              "#X connect 1 0 0 0;",
              "#X connect 2 0 0 1;",
              "#X connect 3 0 0 0;",
              "#X connect 6 0 7 0;",
              "#X connect 7 0 8 0;",
              "#X connect 7 1 11 0;",
              "#X connect 8 0 0 0;",
              "#X connect 9 0 0 0;",
              "#X connect 10 0 0 0;",
              "#X connect 11 0 13 0;",
              "#X connect 11 1 10 0;",
              "#X connect 11 2 9 0;",
              "#X connect 11 3 12 0;",
              "#X connect 11 4 3 0;",
              "#X connect 12 0 0 0;",
              "#X connect 13 0 0 0;")

cast_client = ("#N canvas 1 50 1278 358 10;",
               "#X obj 15 -88 outlet~;",
               "#X msg 17 -232 disconnect;",
               "#X obj 70 -91 outlet~;",
               "#X obj 16 -129 *~ 1;",
               "#X obj 57 -128 *~ 1;",
               "#X obj 17 -365 inlet;",
               "#X obj 17 -338 sel 0 1;",
               "#X msg 103 -126 print;",
               "#X obj 16 -180 oggamp~ 1 2 512;",
               "#X obj 107 -306 delay;",
               "#X obj 133 -329 \$1;",
               "#X obj 133 -353 loadbang;",
               "#X obj 103 -156 sel 1;",
               "#X msg 107 -281 connect %s %s %s" % (options.host, options.listen, options.port),
               "#X connect 1 0 8 0;",
               "#X connect 3 0 0 0;",
               "#X connect 4 0 2 0;",
               "#X connect 5 0 6 0;",
               "#X connect 6 0 1 0;",
               "#X connect 6 1 9 0;",
               "#X connect 7 0 8 0;",
               "#X connect 8 0 3 0;",
               "#X connect 8 1 4 0;",
               "#X connect 8 2 12 0;",
               "#X connect 9 0 13 0;",
               "#X connect 10 0 9 1;",
               "#X connect 11 0 10 0;",
               "#X connect 12 0 7 0;",
               "#X connect 13 0 8 0;",
               "#X coords 0 358 1 357 50 40 0;")

files = [(open("/home/pi/.radio/%s/station.pd"         % station, "w"), main),
         (open("/home/pi/.radio/%s/station_server~.pd" % station, "w"), cast_server),
         (open("/home/pi/.radio/%s/station_client~.pd" % station, "w"), cast_client)]

for (f, s) in files:
    f.write("\n".join(s))
    f.close()

#from subprocess import call
print "="*20
print "Starting with /home/pi/.radio/%s/station.pd" % station
print "log file at /home/pi/.radio/%s/station.log" % station
print "="*20
call(["pd-extended", "-nogui", "-noadc", "-nomidi", "-path", "/home/pi/Github/webcastPD", "/home/pi/.radio/%s/station.pd" % (station)])
