#!/bin/python

from optparse import OptionParser
from subprocess import call

# PROGRAMA PRINCIPAL
PROG = "webcastPD runtime"
VERSION = "0.0.2"
description = "Script python para realização de um streaming em uma rede remota"
parser = OptionParser(usage='usage: %prog [OPTIONS, [ARGS]]',
                      version='%s %s' % (PROG, VERSION),
                      description=description)

# Opcoes do programa
opt =  [("H", "host", None, "host, ou ip do servidor que realizara o streaming (p.e., giss.tv ou 192.168.0.1)"),
        ("m", "music-path", None, "caminho da pasta local contendo uma lista de musicas"),
        ("l", "listen", None, "caminho do ponto de montagem a ser realizado o streaming [suporte a vorbis] (p.e. listen.ogg)"), 
        ("p", "port", None, "porta de servico (p.e. 8000 ou 8001)"),
        ("x", "password", None, "senha do servidor giss.tv"),
        
    ]

# Create a list of tuples
# to create a list of options
for word in opt:
    v = "_".join(word[1].split("-"))
    a = "-%s" % word[0]
    b = "--%s" % word[1]
    if word[2] != None:
        parser.add_option(a, b, action=word[2], help=word[3], dest=v, default=False)
        #elif word[1] == "measures":
        #    parser.add_option(a, b, action=word[2], help=word[3], dest=v, default=False, nargs=2)
    else:
        parser.add_option(a, b, help=word[3], dest=v, default=False)

# Capturar os argumentos passados pelo 
(options, args) = parser.parse_args()

main = ("#N canvas 1 50 638 359 10;",
        "#X text 0 0 ITS A GENERATED PATCH. DO NOT MODIFY!;", 
        "#X obj 1 77 cast.player~ "+options.music_path+" ;", # p.e. /home/pi/Musics
        "#X obj 1 37 tgl 15 0 empty empty empty 17 7 0 10 -262144 -1 -1 0 1;",
        "#X obj 1 107 gen_cast.server.simple~;", 
        "#X obj 0 131 gen_cast.client.simple~ 5000;",
        "#X obj 1 18 loadbang;",
        "#X obj 1 56 t f f;",
        "#X obj 0 159 dac~;",
        "#X msg 42 43 \; pd dsp \$1;", 
        "#X connect 1 0 3 0;",
        "#X connect 1 1 3 1;", 
        "#X connect 2 0 6 0;",
        "#X connect 3 0 4 0;",
        "#X connect 4 0 7 0;",
        "#X connect 4 1 7 1;", 
        "#X connect 4 2 1 0;", 
        "#X connect 5 0 2 0;",
        "#X connect 6 0 3 2;", 
        "#X connect 6 1 8 0;")

cast_server= ("#N canvas 1 50 1278 358 10;",
              "#X obj 36 61 oggcast~ 2 512;",
              "#X obj 37 32 inlet~;",
              "#X obj 116 30 inlet~;",
              "#X msg 412 87 server 1;",
              "#X obj 36 126 print cast.server.simple~ :;",
              "#X obj 118 157 print cast.server.simple~ (frame):;",
              "#X obj 338 13 inlet;",
              "#X obj 338 37 sel 0 1;"
              "#X msg 257 32 disconnect;",
              "#X msg 367 143 vorbis 44100 2 133 128 96;",
              "#X msg 359 171 print;",
              "#X obj 339 60 t b b b b b;",
              "#X msg 392 114 passwd "+options.password+" ;",
              "#X msg 317 211 connect "+options.host+" "+options.listen+" "+options.port+" ;",
              "#X obj 36 188 outlet;",
              "#X connect 0 0 4 0;",
              "#X connect 0 0 14 0;",
              "#X connect 0 1 5 0;",
              "#X connect 1 0 0 0;",
              "#X connect 2 0 0 1;",
              "#X connect 3 0 0 0;",
              "#X connect 6 0 7 0;",
              "#X connect 7 0 8 0;",
              "#X connect 7 1 11 0;",
              "#X connect 8 0 0 0;",
              "#X connect 9 0 0 0;",
              "#X connect 10 0 0 0;",
              "#X connect 11 0 13 0;",
              "#X connect 11 1 10 0;",
              "#X connect 11 2 9 0;",
              "#X connect 11 3 12 0;",
              "#X connect 11 4 3 0;",
              "#X connect 12 0 0 0;",
              "#X connect 13 0 0 0;")

cast_client = ("#N canvas 1 440 1278 358 10;",
               "#X obj 21 264 outlet~;",
               "#X msg 23 120 disconnect;",
               "#X obj 76 261 outlet~;",
               "#X obj 22 223 *~ 1;",
               "#X obj 63 224 *~ 1;",
               "#X obj 22 -13 inlet;",
               "#X obj 23 14 sel 0 1;",
               "#X msg 163 111 print;",
               "#X obj 22 190 oggamp~ 1 2 512;",
               "#X obj 191 227 print cast.client.simple~:;",
               "#X msg 193 204 connected;",
               "#X obj 151 178 == 1;",
               "#X msg 159 88 connect "+options.host+" "+options.listen+" "+options.port+" ;",
               "#X obj 85 31 t b b;",
               "#X obj 151 260 == 0;",
               "#X obj 189 281 print cast.client.simple~:;",
               "#X msg 193 258 disconnected;",
               "#X obj 112 53 delay;",
               "#X obj 141 23 \$1;",
               "#X obj 141 -1 loadbang;",
               "#X obj 214 158 bng 15 250 50 0 empty empty empty 17 7 0 10 -262144 -1 -1;",
               "#X obj 108 289 outlet;",
               "#X connect 1 0 8 0;",
               "#X connect 3 0 0 0;",
               "#X connect 4 0 2 0;",
               "#X connect 5 0 6 0;",
               "#X connect 6 0 1 0;",
               "#X connect 6 1 13 0;",
               "#X connect 7 0 8 0;",
               "#X connect 8 0 3 0;",
               "#X connect 8 1 4 0;",
               "#X connect 8 2 11 0;",
               "#X connect 8 2 21 0;",
               "#X connect 10 0 9 0;",
               "#X connect 11 0 10 0;",
               "#X connect 12 0 8 0;",
               "#X connect 13 0 20 0;",
               "#X connect 13 1 17 0;",
               "#X connect 14 0 16 0;",
               "#X connect 16 0 15 0;",
               "#X connect 17 0 20 0;",
               "#X connect 18 0 17 1;",
               "#X connect 19 0 18 0;",
               "#X connect 20 0 12 0;",
               "#X coords 0 358 1 357 50 40 0;")

files = [(open("main.pd", "w"), main)
          open("gen_cast.server.simple~.pd", "w"), cast_server),
          open("gen_cast.client.simple~.pd", "w"), cast_client)]

for (f, s) in files:
    f.write("\n".join(s))
    f.close()

#from subprocess import call
call(["pd-extended", "-nogui", "-noadc", "-alsa", "main.pd"])
